### PR TITLE
Instruct to use rustup/rustc-mozilla on older Debian/Ubuntu (fixes #6145)

### LINKED ISSUE #6145: Version 16.6 is not installed
Compilation error occurs when upgrading from 16.5 to 16.6. I am attaching the installation log. Installed via [pi-apps](https://github.com/Botspot/pi-apps/blob/master/apps/DDNet/install).

**log >>** [install-fail-DDNet.log](https://github.com/ddnet/ddnet/files/10241024/install-fail-DDNet.log)

OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
rustc-mozilla doesn't exist on all ubuntu versions

**Comment by Chairn** [comment]
I believe rustc should be default as it's available everywhere and specify to use rustup directly on older distros

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
I think a better URL for rustup is https://rustup.rs/, it directly provides installation instructions. I couldn't find that link on the page you linked.

**Comment by Chairn** [comment]
bors r+
Thanks :)
