### ISSUE TITLE
Version 16.6 is not installed

### ISSUE THREAD

**Issue by Rak1ta** [ddnet/ddnet#6145]
Compilation error occurs when upgrading from 16.5 to 16.6. I am attaching the installation log. Installed via [pi-apps](https://github.com/Botspot/pi-apps/blob/master/apps/DDNet/install).

**log >>** [install-fail-DDNet.log](https://github.com/ddnet/ddnet/files/10241024/install-fail-DDNet.log)

OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8

**Comment by Jupeyy** [comment]
probs relevant part
```
  Compiling cxxbridge-macro v1.0.71
error[E0658]: `if` is not allowed in a `const fn`
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/cxxbridge-macro-1.0.71/src/syntax/discriminant.rs:169:19
    |
169 |               sign: if i < 0 {
    |  ___________________^
170 | |                 Sign::Negative
171 | |             } else {
172 | |                 Sign::Positive
173 | |             },
    | |_____________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error[E0277]: the trait bound `K: std::cmp::Eq` is not satisfied
  --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/cxxbridge-macro-1.0.71/src/syntax/map.rs:95:26
   |
93 |     impl<K, V> UnorderedMap<K, V> {
   |          - help: consider restricting this bound: `K: std::cmp::Eq`
94 |         pub fn new() -> Self {
95 |             UnorderedMap(HashMap::new())
   |                          ^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `K`
   |
   = note: required by `std::collections::HashMap::<K, V>::new`

error[E0277]: the trait bound `K: std::hash::Hash` is not satisfied
  --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/cxxbridge-macro-1.0.71/src/syntax/map.rs:95:26
   |
93 |     impl<K, V> UnorderedMap<K, V> {
   |          - help: consider restricting this bound: `K: std::hash::Hash`
94 |         pub fn new() -> Self {
95 |             UnorderedMap(HashMap::new())
   |                          ^^^^^^^^^^^^^^ the trait `std::hash::Hash` is not implemented for `K`
   |
   = note: required by `std::collections::HashMap::<K, V>::new`

error: aborting due to 3 previous errors

```



rust version too old?

@heinrich5991 maybe knows more

**Comment by Rak1ta** [comment]
@Jupeyy [rustc](https://packages.debian.org/ru/buster/rustc)

**Comment by Jupeyy** [comment]
i'd try to use rust-up (https://rustup.rs/) and try again

**Comment by def-** [comment]
Other than that, how does DDNet run on RPi?

**Comment by Zwelf** [comment]
Can you try [rustc-mozilla](https://packages.debian.org/buster/rustc-mozilla), which packages a newer version of Rust, used to compile Firefox on Debian.

**Comment by Rak1ta** [comment]
@def- Works great, no crashes

**Comment by Rak1ta** [comment]
@Zwelf If you use rustc-mozilla on Debian Buster, then the installation proceeds correctly.

**Comment by def-** [comment]
We should at least print a nice warning that instructs you to install a more recent rustc version when your is too out of date. (And then test with the minimum required version too to make sure it keeps working.)

**Comment by Rak1ta** [comment]
@def- Can you add to the instructions as a recommendation to use an alternative package? On Buster, packages are almost never updated.

**Comment by def-** [comment]
Done: https://github.com/ddnet/ddnet/pull/6146

How many FPS do you get? Does Vulkan renderer work?

**Comment by Jupeyy** [comment]
its quite possible that we disabled vk for 32bit so we dont have to deal with any kinds of problems ^^
But maybe if u manually enable, tho i dunno if these old PIs have a vk driver :D

**Comment by Rak1ta** [comment]
@def- Everything feels like 60fps. 

```
pi@raspberrypi:~ $ DDNet
2022-12-16 16:52:27 I engine: running on unix-linux-arm
2022-12-16 16:52:27 I engine: arch is little endian
2022-12-16 16:52:27 I engine: operation system version: Linux 5.10.103-v7l+ (armv7l, #1529 SMP Tue Mar 8 12:24:00 GMT 2022); "Raspbian GNU/Linux 10 (buster)"
2022-12-16 16:52:27 I storage: couldn't open storage.cfg
2022-12-16 16:52:27 I storage: using standard paths
2022-12-16 16:52:27 I storage: added path '$USERDIR' ('/home/pi/.local/share/ddnet')
2022-12-16 16:52:27 I storage: added path '$DATADIR' ('/usr/local/share/ddnet/data')
2022-12-16 16:52:27 I storage: added path '$CURRENTDIR' ('/home/pi')
2022-12-16 16:52:27 I http: libcurl version 7.64.0 (compiled = 7.64.0)
2022-12-16 16:52:27 I console: executing 'settings_ddnet.cfg'
2022-12-16 16:52:27 I client: starting...
2022-12-16 16:52:27 I sdl: SDL version 2.0.10 (compiled = 2.0.15)
2022-12-16 16:52:28 I gfx: Created Vulkan 1.1 context.
2022-12-16 16:52:28 I gfx: unable to create window: Vulkan support is either not configured in SDL or not available in current SDL video driver (x11) or platform
2022-12-16 16:52:28 I sdl: SDL version 2.0.10 (compiled = 2.0.15)
2022-12-16 16:52:28 I gfx: Created OpenGL 3.0 context.
2022-12-16 16:52:28 I gfx: unable to create graphic context: Could not create GL context: GLXBadFBConfig
2022-12-16 16:52:28 I sdl: SDL version 2.0.10 (compiled = 2.0.15)
2022-12-16 16:52:28 I gfx: Created OpenGL 2.1 context.
2022-12-16 16:52:28 I opengl: Vendor string: Broadcom
2022-12-16 16:52:28 I opengl: Version string: 2.1 Mesa 19.3.2
2022-12-16 16:52:28 I gfx: GPU vendor: Broadcom
2022-12-16 16:52:28 I gfx: GPU renderer: V3D 4.2
2022-12-16 16:52:28 I gfx: GPU version: 2.1 Mesa 19.3.2
```

**Comment by def-** [comment]
Thanks for the info, good to see the fallback working correctly. I also addressed the compiler warnings I saw in your build log as part of https://github.com/ddnet/ddnet/pull/6147

**Comment by def-** [comment]
Are you planning to add DDNet in https://github.com/Botspot/pi-apps ?

**Comment by Rak1ta** [comment]
@def- It's been added there for a long time.

**Comment by Chairn** [comment]
Don't forget to update website there https://github.com/Botspot/pi-apps/blob/master/apps/DDNet/website
Official website is now https://ddnet.org
