### ISSUE TITLE
Win32 build fails with Discord

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#9954]
```
/home/deen/isos/ddnet/ddnet-source/src/engine/client/discord.cpp: In member function ‘bool CDiscord::Init(FDiscordCreate)’:
/home/deen/isos/ddnet/ddnet-source/src/engine/client/discord.cpp:44:53: error: invalid conversion from ‘void (*)(void*, const char*)’ to ‘void (__attribute__((stdcall)) *)(void*, const char*)’ [-fpermissive]
   44 |                 m_ActivityEvents.on_activity_join = &CDiscord::OnActivityJoin;
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     void (*)(void*, const char*)
```

**Comment by def-** [comment]
Caused by #9812 @KebsCS
