### ISSUE TITLE
make -j1 fails: src/game/gamecore.h:12:10: fatal error: generated/protocol.h: No such file or directory

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#11162]
```
In file included from /ddnet-source/src/game/gamecore.cpp:3:
/ddnet-source/src/game/gamecore.h:12:10: fatal error: generated/protocol.h: No such file or directory
   12 | #include <generated/protocol.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
With more parallelism it works, so I assume the dependency between gamecore.cpp -> protocol.h isn't encoded properly in cmake.

This is causing the official (nightly) builds to fail.

**Comment by KebsCS** [comment]
Also having a lot of problems with the generated files lately. IDE not finding them, sometimes can't build etc

**Comment by AssassinTee** [comment]
I was able to reproduce the same issue on unique in github actions with ASAN

**Comment by heinrich5991** [comment]
Likely caused by https://github.com/ddnet/ddnet/pull/11136#issuecomment-3454988601.
